webtalk_init -webtalk_dir D:\\study\\embled\\project1_v\\project1_v.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期一 四月 20 21:57:02 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "207600880_1777491182_0_870" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7n54hde01ncdsod638sl8rkruf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1429538081678" -context "sdk\\\\hardware/1429538081678"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1429538081678"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1429538081678"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.2" -context "sdk\\\\hardware/1429538081678"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1429538081678"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1429538081678"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1429538081678"
webtalk_transmit -clientid 588766797 -regid "207600880_1777491182_0_870" -xml D:\\study\\embled\\project1_v\\project1_v.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\study\\embled\\project1_v\\project1_v.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\study\\embled\\project1_v\\project1_v.sdk\\webtalk\\sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
